### ISSUE TITLE
A guide?

### ISSUE THREAD

**Issue by scillablade** [BotanKurd/GDCore#1]
I am interesting in to test this program, is a kind of bot for Dofus 1.29, right?

If your answers is yes, I want to ask you for a guide to set up and use it please.

**Comment by BotanAtomic** [comment]
Hello, its not a Dofus bot but à Dofus game server, for use you must have
local server database  (Mysql). If you have, you just had to clone project,
modifie the configuration file and start the program (dont forget install
database)
