### ISSUE TITLE
How to get missing database java file in graviton - common ?

### ISSUE THREAD

**Issue by Coniface** [BotanKurd/GDCore#2]
The project won't build because it has several imports like
`import static org.graviton.database.jooq.game.tables.HousesData.HOUSES_DATA;`

It looks that there is a missing package org.graviton.database.jooq.game as I only have the login database in this package.

Am I missing something here?

**Comment by BotanAtomic** [comment]
Oh yes, i'm sorry, i'm going to refresh project. Sorry

**Comment by projectsin** [comment]
@BotanKurd

**Comment by Coniface** [comment]
So isn't it an SQL script + the game Database entities missing from the project ?

**Comment by happybydefault** [comment]
Hi, I'm possibly an ignorant about this kind of stuff, and I couldn't find the 'game' mysql database. Is this somehow related to this same github issue? How can I get it?
Thanks in advance 🙂

**Comment by BotanAtomic** [comment]
Oh yes, i'm going to upload that ! Sorry

Best regards, Botan

**Comment by BotanAtomic** [comment]
Done.
